#' Plot simulated pedigrees
#'
#' Plot method for objects of class `ped`. Basically this function is a wrapper
#' for the [kinship2::plot.pedigree()] function from the `kinship2` package.
#'
#' @param x Object of class `ped` created by functions [sim_pedigree()] or
#' [sim_pedigree_problem()]
#' @param ... Other arguments passed to the [kinship2::plot.pedigree()] method
#' from the `kinship2` package.
#'
#' @return Returns the invisible list generated by the method plot.pedigree
#' from the kinship2 package.
#'
#' @seealso [kinship2::plot.pedigree()]
#'
#' @examples
#' set.seed(1)
#' plot(sim_pedigree(generations = 3, tfr = 3))
#'
#' @export
#' @md
plot.ped <- function(x, ...) {
  x <- convert2kinship2(x)
  kinship2::plot.pedigree(x, ...)
}
